version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
artifacts:
  files:
    - '**/*'
  name: products-api-$(date +%Y-%m-%d)
cache:
  paths:
    - '~/.npm'